### ISSUE TITLE
Support for debian buster?

### ISSUE THREAD

**Issue by duncanmmacleod** [lscsoft/docker-ligo-base#5]
It would be great to have `ligo/base:buster` and `ligo/software:buster` images to play around with, is there a change to get this supported? I have no idea how to write Dockerfiles, otherwise would offer to help.

**Comment by skymoo** [comment]
Buster is still in development and there aren't any `buster` repositories for LSCSoft yet so essentially `ligo/base:buster` would be `debian:buster`. When there are more repositories available for `buster`, and when it is more stable, we can add an official `buster` container.

**Comment by tpdownes** [comment]
Resolved by #7
